#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

source `pipenv --venv`/bin/activate

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate --noinput
gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
