# Generated by Django 2.2.9 on 2020-01-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20200104_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='published',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='permalink',
            field=models.URLField(blank=True, db_index=True, default=True),
        ),
    ]
